export { DynamoDBModule } from './module/dynamodb.module'
export { InjectDDBModel, ReturnDDBModel } from './module/dynamodb.decorators'
export { embed } from './util/embed'
export {
  attribute as Attribute,
  hashKey as HashKey,
  rangeKey as RangeKey,
  table as Table,
  autoGeneratedHashKey as AutoGeneratedHashKey,
  versionAttribute as VersionAttribute,
} from '@aws/dynamodb-data-mapper-annotations'
export * from 'dynamoose'
